name: Rust Documentation

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable

    - name: Clone repository
      uses: actions/checkout@v3

    - name: Build documentation
      run: |
        cargo doc
        ln -s ./target/doc/learning_rust/index.html ./target/doc


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc

